## Preprocessing

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN'.
application_df = application_df.drop(columns=['EIN'])

In [4]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [5]:
# Look at NAME value counts for binning
name_counts = application_df['NAME'].value_counts()
name_counts

PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: NAME, Length: 19568, dtype: int64

In [6]:
name_to_replace = list(name_counts[name_counts<10].index)

# Replace in dataframe
for name in name_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(name,"Other")

# Check to make sure binning was successful
application_df['NAME'].value_counts()

Other                                      21022
PARENT BOOSTER USA INC                      1260
TOPS CLUB INC                                765
UNITED STATES BOWLING CONGRESS INC           700
WASHINGTON STATE UNIVERSITY                  492
                                           ...
CASCADE 4-H FOUNDATION                        10
FREE & ACCEPTED MASONS OF WASHINGTON          10
NEW MEXICO GARDEN CLUBS INC                   10
NATIONAL ASSOCIATION OF HISPANIC NURSES       10
UNION OF CALIFORNIA STATE WORKERS             10
Name: NAME, Length: 223, dtype: int64

In [7]:
# Look at APPLICATION_TYPE value counts for binning
application_types = application_df['APPLICATION_TYPE'].value_counts()
application_types

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [8]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_types[application_types<500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [9]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [10]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_counts = classification_counts[classification_counts>1]
class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [11]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_counts[classification_counts <1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [12]:
# Convert categorical data to numeric with `pd.get_dummies`
application_dummies_df = pd.get_dummies(application_df)
application_dummies_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,NAME_ALABAMA TREASURE FOREST ASSOCIATION,NAME_ALPHA PHI SIGMA,NAME_ALPHA PHI SIGMA INC,NAME_ALTRUSA INTERNATIONAL FOUNDATION INC,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [13]:
# Split our preprocessed data into our features and target arrays
y = application_dummies_df['IS_SUCCESSFUL'].values
X = application_dummies_df.drop(columns='IS_SUCCESSFUL').values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [14]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [15]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len( X_train_scaled[0])
hidden_nodes_layer1=80
hidden_nodes_layer2=30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim = number_input_features, activation = "relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation = "relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                21360

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 23821 (93.05 KB)
Trainable params: 23821 (93.05 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [16]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [17]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 6s 5ms/step - loss: 0.4752 - accuracy: 0.7706
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4440 - accuracy: 0.7851
Epoch 3/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4391 - accuracy: 0.7866
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4370 - accuracy: 0.7879
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4353 - accuracy: 0.7878
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4344 - accuracy: 0.7904
Epoch 7/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4338 - accuracy: 0.7896
Epoch 8/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4329 - accuracy: 0.7893
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4321 - accuracy: 0.7909
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4315 - accuracy: 0.7914
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4309 - accuracy: 0.7902
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4308 - accuracy: 0.7916
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4297 - accuracy: 0.7922
Epoch 14/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4291 - accuracy: 0.7914
Epoch 15/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4289 - accuracy: 0.7924
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4287 - accuracy: 0.7924
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4281 - accuracy: 0.7929
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4270 - accuracy: 0.7946
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4273 - accuracy: 0.7936
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4266 - accuracy: 0.7930
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4264 - accuracy: 0.7949
Epoch 22/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4258 - accuracy: 0.7944
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4250 - accuracy: 0.7950
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4249 - accuracy: 0.7941
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4248 - accuracy: 0.7936
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4244 - accuracy: 0.7954
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4236 - accuracy: 0.7947
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4234 - accuracy: 0.7956
Epoch 29/50
804/804 [==============================] - 3s 3ms/step - loss: 0.4231 - accuracy: 0.7956
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4230 - accuracy: 0.7952
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4229 - accuracy: 0.7962
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4226 - accuracy: 0.7959
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4217 - accuracy: 0.7964
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4220 - accuracy: 0.7955
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4218 - accuracy: 0.7969
Epoch 36/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4215 - accuracy: 0.7968
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4210 - accuracy: 0.7975
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4205 - accuracy: 0.7971
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4204 - accuracy: 0.7962
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4204 - accuracy: 0.7975
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4203 - accuracy: 0.7969
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4195 - accuracy: 0.7984
Epoch 43/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4196 - accuracy: 0.7968
Epoch 44/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4194 - accuracy: 0.7984
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4190 - accuracy: 0.7986
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4188 - accuracy: 0.7974
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4190 - accuracy: 0.7984
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4186 - accuracy: 0.7983
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.4187 - accuracy: 0.7984
Epoch 50/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4184 - accuracy: 0.7985

In [18]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.4701 - accuracy: 0.7787 - 521ms/epoch - 2ms/step
Loss: 0.47008439898490906, Accuracy: 0.7786588668823242

In [24]:
# Export our model to HDF5 file
from google.colab import files
nn.save('AlphabetSoupCharity_Optimization.h5')
files.download('AlphabetSoupCharity_Optimization.h5')